### ISSUE TITLE
не создаются подпапки

### ISSUE THREAD

**Issue by anatolytkach** [vinser/flibgo#3]
Я проделал действия из инструкции ниже, но подпапки не создались:
--------------------------------------------
"В файле docker-compose.yml укажите папку, например, "books", в котором будут храниться и обрабатываться файлы FB2 и zip-архивы с файлами
В папке будут созданы три подпапки..."
-------------------------------------------
Возможно, я использовал неправильный формат для указания папки. Подскажите правильный, плз: мои книги лежат в папке "knigi" на внешнем диске с названием "USB".

Также, при запуске я получаю такую ошибку:
Error response from daemon: Mounts denied: 
The path /applications/flibgo-master is not shared from the host and is not known to Docker.
Подскажите плз, как решить: дело в том, что этот путь уже добавлен у меня в Docker.

**Comment by vinser** [comment]
В файле docker-compose.yml укажите папку... Например, в Windows  надо как-то так поправить:
 
 volumes:
      - d:/knigi:/books
      # - /your/path/to/books:/books
      # ^^^^^^^^^^^^^^^ - path to your book stock folders

где d: - ваш USB диск
